baseURL = 'https://BigKahunaBurger87.github.io/'
languageCode = 'en-us'
title = 'BigKahunaBurger87 - Walkthroughs & Tools'
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowToc = true
    
    [params.homeInfoParams]
        Title = "Welcome to BigKahunaBurger87's Security Blog"
        Content = "Here you'll find my HackTheBox walkthroughs, custom Python tools, and security research."

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/BigKahunaBurger87"

[menu]
    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 10
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 20
    [[menu.main]]
        identifier = "tools"
        name = "My Tools"
        url = "https://github.com/BigKahunaBurger87?tab=repositories"
        weight = 30
